image: crowdar/lippia:3.2.1.1

pipelines:
  branches:
    master:  
      - step:
          name: Publish code to Github
          services:
            - docker
          trigger: automatic
          script:
            - mvn clean test -PLocalHeadless -Dcucumber.tags=@Smoke
            - export PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
            - git tag $PROJECT_VERSION
            - git push origin
            - git remote add github https://$GITHUB_USER_E:$GITHUB_TOKEN_E@github.com/Crowdar/lippia-web-sample-project.git
            - git push -u github
      
